# Copyright (c) 2019-2020, Pete Batard <pete@akeo.ie>
# SPDX-License-Identifier: BSD-3-Clause

image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'
    - '**/*.txt'

environment:
  ATF_VERSION: 2.3

install:
  - sh: sudo apt-get update -qq
  - sh: sudo -E apt-get install -y gcc-aarch64-linux-gnu

before_build:
  - ps: Start-FileDownload https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/snapshot/trusted-firmware-a-$env:ATF_VERSION.tar.gz
  - sh: tar -xzf trusted-firmware-a-$ATF_VERSION.tar.gz

build_script:
  - sh: cd trusted-firmware-a-$ATF_VERSION
  - sh: export CROSS_COMPILE=/usr/bin/aarch64-linux-gnu-
  - sh: make PLAT=rpi3 RPI3_PRELOADED_DTB_BASE=0x10000 PRELOADED_BL33_BASE=0x30000 SUPPORT_VFP=1 RPI3_USE_UEFI_MAP=1 DEBUG=0 fip all
  - sh: make PLAT=rpi4 RPI3_PRELOADED_DTB_BASE=0x1F0000 PRELOADED_BL33_BASE=0x20000 SUPPORT_VFP=1 DEBUG=0 all

after_build:
  - sh: sha256sum build/rpi3/release/bl1.bin
  - sh: sha256sum build/rpi3/release/fip.bin
  - sh: sha256sum build/rpi4/release/bl31.bin

artifacts:
  - path: trusted-firmware-a-$(ATF_VERSION)/build/rpi3/release/bl1.bin
    name: Raspberry Pi 3 BL1 image
    type: file
  - path: trusted-firmware-a-$(ATF_VERSION)/build/rpi3/release/fip.bin
    name: Raspberry Pi 3 FIP image
    type: file
  - path: trusted-firmware-a-$(ATF_VERSION)/build/rpi4/release/bl31.bin
    name: Raspberry Pi 4 BL31 image
    type: file

deploy:
  release: v$(ATF_VERSION)
  description: Raspberry Pi Arm Trusted Firmware v$(ATF_VERSION)
  provider: GitHub
  auth_token:
    secure: w5YuQOim+G+U7FxxrL0BH6t0trCWKCs9DMZlF4xqF2XGC6SymzwaJrPWrKeeJHPK
  artifact: /.*\.bin/
  draft: false
  prerelease: false
